version: '3'
services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwe1209
    volumes:
      - ./db/init_databases.sh:/docker-entrypoint-initdb.d/10_init_databases.sh

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
        - "3000:3000"
    volumes:
      - .:/mnt/applandql
    depends_on:
      - db